Repository AlistGo/docs, pull requests merged in 2023-08, with the labels that each got.

#247 Fix typo & improve format
  docs/guide/drivers/aliyundrive.md
  docs/zh/guide/drivers/115.md
  docs/zh/guide/drivers/123.md
  docs/zh/guide/drivers/139.md
  docs/zh/guide/drivers/189.md
  docs/zh/guide/drivers/Alist V2 V3.md
  docs/zh/guide/drivers/SMB.md
  docs/zh/guide/drivers/Seafile.md
  docs/zh/guide/drivers/Terabox.md
  docs/zh/guide/drivers/Trainbit.md
  docs/zh/guide/drivers/UrlTree.md
  docs/zh/guide/drivers/aliyundrive.md
  docs/zh/guide/drivers/aliyundrive_open.md
  docs/zh/guide/drivers/baidu.md
  docs/zh/guide/drivers/baidu.photo.md
  docs/zh/guide/drivers/baidu_share.md
  docs/zh/guide/drivers/dropbox.md
  docs/zh/guide/drivers/ftp.md
  docs/zh/guide/drivers/googledrive.md
  docs/zh/guide/drivers/googlephotos.md
  docs/zh/guide/drivers/lanzou.md
  docs/zh/guide/drivers/local.md
  docs/zh/guide/drivers/mediatrack.md
  docs/zh/guide/drivers/mega.md
  docs/zh/guide/drivers/mopan.md
  docs/zh/guide/drivers/onedrive.md
  docs/zh/guide/drivers/onedrive_app.md
  docs/zh/guide/drivers/pikpak.md
  docs/zh/guide/drivers/quark.md
  docs/zh/guide/drivers/s3.md
  docs/zh/guide/drivers/sftp.md
  docs/zh/guide/drivers/teambition.md
  docs/zh/guide/drivers/thunder.md
  docs/zh/guide/drivers/uss.md
  docs/zh/guide/drivers/webdav.md
  docs/zh/guide/drivers/wopan.md
  docs/zh/guide/drivers/yandex.md
Labels: size/M

#253 feat(crypt): update doc
  docs/guide/drivers/Crypt.md
  docs/zh/guide/drivers/Crypt.md
Labels: size/M

#254 feat(crypt) fix doc typos
  docs/guide/drivers/Crypt.md
Labels: size/S

#256 Update sso.md
  docs/guide/advanced/sso.md
  docs/zh/guide/advanced/sso.md
Labels: size/XS

#249 增加支持webdav的X-plore和Joplin
  docs/guide/webdav.md
  docs/zh/guide/webdav.md
Labels: size/XS

#231 add a free tool on Mac which support mount WebDav
  docs/guide/webdav.md
  docs/zh/guide/webdav.md
Labels: size/XS

#259 修改UC网盘为官方的名字
  docs/guide/README.md
  docs/zh/guide/README.md
Labels: size/XS

#257 docs: update docs
  docs/.vuepress/public/img/drivers/weiyun/weiyun_cookie.png
  docs/.vuepress/theme.ts
  docs/config/global.md
  docs/config/other.md
  docs/faq/howto.md
  docs/guide/advanced/alias.md
  docs/guide/drivers/123.md
  docs/guide/drivers/Crypt.md
  docs/guide/drivers/alias.md
  docs/guide/drivers/aliyundrive_open.md
  docs/guide/drivers/baidu.md
  docs/guide/drivers/weiyun.md
  docs/guide/install/manual.md
  docs/zh/config/global.md
  docs/zh/config/other.md
  docs/zh/faq/howto.md
  docs/zh/guide/advanced/alias.md
  docs/zh/guide/drivers/123.md
  docs/zh/guide/drivers/Crypt.md
  docs/zh/guide/drivers/alias.md
  docs/zh/guide/drivers/aliyundrive_open.md
  docs/zh/guide/drivers/baidu.md
  docs/zh/guide/drivers/baidu_share.md
  docs/zh/guide/drivers/weiyun.md
  docs/zh/guide/install/docker.md
  docs/zh/guide/install/manual.md
Labels: size/L

#258 add alist V3 API document
  docs/.vuepress/sidebar/en.ts
  docs/.vuepress/sidebar/zh.ts
  docs/guide/api/README.md
  docs/guide/api/admin/driver.md
  docs/guide/api/admin/meta.md
  docs/guide/api/admin/setting.md
  docs/guide/api/admin/storage.md
  docs/guide/api/admin/task.md
  docs/guide/api/admin/user.md
  docs/guide/api/auth.md
  docs/guide/api/fs.md
  docs/guide/api/public.md
  docs/zh/guide/api/README.md
  docs/zh/guide/api/admin/driver.md
  docs/zh/guide/api/admin/meta.md
  docs/zh/guide/api/admin/setting.md
  docs/zh/guide/api/admin/storage.md
  docs/zh/guide/api/admin/task.md
  docs/zh/guide/api/admin/user.md
  docs/zh/guide/api/auth.md
  docs/zh/guide/api/fs.md
  docs/zh/guide/api/public.md
Labels: size/XXL
