Repository AlistGo/docs, pull requests merged in 2023-11, with the labels that each got.

#286 Use the new Github proxy source
  docs/.vuepress/public/v2.sh
  docs/.vuepress/public/v3.sh
Labels: size/XS

#285 add 115 driver share link doc
  docs/guide/drivers/115_share.md
  docs/guide/drivers/mega.md
  docs/zh/guide/drivers/115_share.md
  docs/zh/guide/drivers/mega.md
Labels: size/L

#291 Docd: update
  .npmrc
  docs/.vuepress/public/img/drivers/115/add_error.png
  docs/.vuepress/public/img/drivers/115/file_cid.png
  docs/.vuepress/public/img/drivers/115/root_cid.png
  docs/.vuepress/public/img/drivers/115/url_demo.png
  docs/.vuepress/public/img/drivers/chaoxing/chaoxing_bbsid.png
  docs/.vuepress/public/img/drivers/chaoxing/chaoxing_folder_id.gif
  docs/.vuepress/public/img/drivers/vtencent/vtencent_cookie.png
  docs/.vuepress/public/v2.sh
  docs/.vuepress/public/v3.sh
  docs/.vuepress/theme.ts
  docs/config/configuration.md
  docs/config/global.md
  docs/config/other.md
  docs/guide/README.md
  docs/guide/advanced/meta.md
  docs/guide/advanced/user.md
  docs/guide/drivers/115.md
  docs/guide/drivers/115_share.md
  docs/guide/drivers/aliyundrive_open.md
  docs/guide/drivers/chaoxing.md
  docs/guide/drivers/s3.md
  docs/guide/drivers/vtencent.md
  docs/guide/install/manual.md
  docs/guide/install/script.md
  docs/zh/config/configuration.md
  docs/zh/config/global.md
  docs/zh/config/other.md
  docs/zh/guide/README.md
  docs/zh/guide/advanced/meta.md
  docs/zh/guide/advanced/user.md
  docs/zh/guide/drivers/115.md
  docs/zh/guide/drivers/115_share.md
  docs/zh/guide/drivers/alias.md
  docs/zh/guide/drivers/aliyundrive_open.md
  docs/zh/guide/drivers/chaoxing.md
  docs/zh/guide/drivers/s3.md
  docs/zh/guide/drivers/vtencent.md
  docs/zh/guide/install/manual.md
  docs/zh/guide/install/script.md
  package.json
  pnpm-lock.yaml
Labels: size/XXL

#288 add VidHub iOS/tvOS version
  docs/guide/webdav.md
  docs/zh/guide/webdav.md
Labels: size/S

#293 Add apifox online api tool
  docs/.vuepress/public/img/api/apifox.png
  docs/guide/api/apifox.md
  docs/guide/api/auth.md
  docs/guide/api/fs.md
  docs/guide/api/public.md
  docs/zh/guide/api/apifox.md
  docs/zh/guide/api/auth.md
  docs/zh/guide/api/fs.md
  docs/zh/guide/api/public.md
Labels: size/M
