Repository AlistGo/docs, pull requests merged in 2024-01, with the labels that each got.

#311 add config and ilanzou
  docs/.vuepress/public/img/drivers/lanzou/ilanzou_folder.png
  docs/config/configuration.md
  docs/guide/README.md
  docs/guide/drivers/aliyundrive.md
  docs/guide/drivers/aliyundrive_open.md
  docs/guide/drivers/ilanzou.md
  docs/guide/install/manual.md
  docs/guide/webdav.md
  docs/zh/config/configuration.md
  docs/zh/guide/README.md
  docs/zh/guide/drivers/aliyundrive.md
  docs/zh/guide/drivers/aliyundrive_open.md
  docs/zh/guide/drivers/ilanzou.md
  docs/zh/guide/install/manual.md
  docs/zh/guide/webdav.md
  package.json
  pnpm-lock.yaml
Labels: size/XXL

#306 fix typo in rapid_upload.md
  docs/guide/advanced/rapid_upload.md
  docs/zh/guide/advanced/rapid_upload.md
Labels: size/XS

#299 docs: use firefox capture cookies may cause problem
  docs/guide/drivers/quark.md
  docs/zh/guide/drivers/quark.md
Labels: size/XS

#301 Docs : update desktop-release download proxy url
  docs/.vuepress/components/Desktop.vue
Labels: size/XS

#300 refine rapid_upload.md
  docs/zh/guide/advanced/rapid_upload.md
Labels: size/XS

#295 修改docker重启策略为unless-stopped
  docs/.vuepress/public/docker-compose.yml
  docs/guide/install/docker.md
  docs/zh/guide/install/docker.md
Labels: size/M

#305 Update webdav.md
  docs/guide/webdav.md
  docs/zh/guide/webdav.md
Labels: size/S

#312 Add deploy on sealos
  docs/guide/install/paas.md
  docs/zh/guide/install/paas.md
Labels: size/XS

#308 :pencil: webdav 存储添加错误提示及解决方案
  docs/.vuepress/public/img/drivers/webdav/webdav_Security.png
  docs/zh/guide/drivers/webdav.md
Labels: size/XS

#315 Docs: add task info api and format
  docs/guide/api/admin/driver.md
  docs/guide/api/admin/meta.md
  docs/guide/api/admin/setting.md
  docs/guide/api/admin/storage.md
  docs/guide/api/admin/task.md
  docs/guide/api/admin/user.md
  docs/guide/api/apifox.md
  docs/guide/api/auth.md
  docs/guide/api/fs.md
  docs/guide/api/public.md
  docs/zh/guide/api/admin/driver.md
  docs/zh/guide/api/admin/meta.md
  docs/zh/guide/api/admin/setting.md
  docs/zh/guide/api/admin/storage.md
  docs/zh/guide/api/admin/task.md
  docs/zh/guide/api/admin/user.md
  docs/zh/guide/api/auth.md
  docs/zh/guide/api/fs.md
  docs/zh/guide/api/public.md
  pnpm-lock.yaml
Labels: size/XXL
