Repository AlistGo/docs, pull requests merged in 2024-07, with the labels that each got.

#364 Fix: Fix misspelled column name
  docs/zh/guide/advanced/rapid_upload.md
Labels: size/XS

#363 docs：add halacloud and update pikpak & thunder
  docs/.vuepress/public/img/drivers/aliyun/aliyun_api.png
  docs/.vuepress/public/img/drivers/aliyun/aliyun_type.png
  docs/.vuepress/public/img/drivers/halalcloud/halalcloud_add.png
  docs/.vuepress/public/img/drivers/halalcloud/halalcloud_login.png
  docs/.vuepress/public/img/drivers/halalcloud/halalcloud_url.png
  docs/.vuepress/public/img/drivers/xunlei/x_br_add1.png
  docs/.vuepress/public/img/drivers/xunlei/x_br_add2.png
  docs/.vuepress/public/img/drivers/xunlei/x_br_error.png
  docs/.vuepress/public/img/drivers/xunlei/x_br_foled.png
  docs/.vuepress/theme.ts
  docs/config/global.md
  docs/faq/error.md
  docs/guide/README.md
  docs/guide/advanced/ipa.md
  docs/guide/advanced/offline-download.md
  docs/guide/drivers/115.md
  docs/guide/drivers/aliyundrive_open.md
  docs/guide/drivers/halalcloud.md
  docs/guide/drivers/pikpak.md
  docs/guide/drivers/thunder.md
  docs/zh/config/configuration.md
  docs/zh/config/global.md
  docs/zh/faq/error.md
  docs/zh/guide/README.md
  docs/zh/guide/advanced/ipa.md
  docs/zh/guide/advanced/offline-download.md
  docs/zh/guide/drivers/115.md
  docs/zh/guide/drivers/aliyundrive_open.md
  docs/zh/guide/drivers/halalcloud.md
  docs/zh/guide/drivers/pikpak.md
  docs/zh/guide/drivers/thunder.md
Labels: size/XXL

#359 向 ecosystem 增加一个整合了 Aria2 和 qBit 的 Alist 容器
  ecosystem.json
Labels: size/XS

#356 docs: update common.md for alist-proxy worker usage
  docs/guide/drivers/common.md
  docs/zh/guide/drivers/common.md
Labels: size/XS

#354 添加了 Terabox(海外百度) 的 jsToken 获取说明
  docs/guide/drivers/Terabox.md
  docs/zh/guide/drivers/Terabox.md
Labels: size/S
