Repository AlistGo/docs, pull requests merged in 2024-05, with the labels that each got.

#349 Docs: add type query parameter usage for preview (src alist-org/alist-web#177)
  docs/config/preview.md
  docs/zh/config/preview.md
Labels: size/M

#337 docs: 添加部署时指定时区的方法说明
  docs/guide/install/docker.md
  docs/zh/guide/install/docker.md
Labels: size/XS

#341 Add Google Storage Guide
  docs/.vuepress/public/img/drivers/s3/googleStorage1.png
  docs/.vuepress/public/img/drivers/s3/googleStorage2.png
  docs/.vuepress/public/img/drivers/s3/googleStorage3.png
  docs/.vuepress/public/img/drivers/s3/googleStorage4.png
  docs/guide/drivers/s3.md
  docs/zh/guide/drivers/s3.md
Labels: size/M

#342 添加nginx反向代理中http3配置说明
  docs/zh/guide/install/reverse-proxy.md
Labels: size/S

#345 增加一处使用宝塔面板时应该修改的配置文件
  docs/guide/install/reverse-proxy.md
  docs/zh/guide/install/reverse-proxy.md
Labels: size/S

#334 chore: Revise the text description to make it clearer
  docs/.vuepress/components/HomeAds.vue
  docs/guide/drivers/aliyundrive.md
Labels: size/M

#346 Docs: update API documentation
  docs/guide/api/admin/driver.md
  docs/guide/api/admin/meta.md
  docs/guide/api/admin/setting.md
  docs/guide/api/admin/storage.md
  docs/guide/api/admin/task.md
  docs/guide/api/admin/user.md
  docs/guide/api/auth.md
  docs/guide/api/fs.md
  docs/guide/api/public.md
  docs/zh/guide/api/admin/driver.md
  docs/zh/guide/api/admin/meta.md
  docs/zh/guide/api/admin/setting.md
  docs/zh/guide/api/admin/storage.md
  docs/zh/guide/api/admin/task.md
  docs/zh/guide/api/admin/user.md
  docs/zh/guide/api/auth.md
  docs/zh/guide/api/fs.md
  docs/zh/guide/api/public.md
Labels: size/XXL

#350 Docs: update
  docs/.vuepress/public/img/advanced/s3/s3_logo/s3browser.png
  docs/.vuepress/public/img/advanced/s3/s3_logo/s3drive.png
  docs/.vuepress/public/img/advanced/s3/s3drive.png
  docs/.vuepress/public/img/drivers/163/163_cookie.png
  docs/.vuepress/public/img/drivers/mega/mega_2fa.png
  docs/.vuepress/public/img/drivers/mega/mega_2fa_code.png
  docs/.vuepress/public/img/drivers/mega/mega_add.png
  docs/.vuepress/public/img/drivers/xunlei/xlx_name.jpg
  docs/.vuepress/public/img/drivers/xunlei/xlx_z1.jpg
  docs/.vuepress/public/img/drivers/xunlei/xlx_z2.jpg
  docs/guide/README.md
  docs/guide/advanced/alias.md
  docs/guide/advanced/s3.md
  docs/guide/drivers/123.md
  docs/guide/drivers/139.md
  docs/guide/drivers/163music.md
  docs/guide/drivers/189.md
  docs/guide/drivers/Alist V2 V3.md
  docs/guide/drivers/Crypt.md
  docs/guide/drivers/alias.md
  docs/guide/drivers/mega.md
  docs/guide/drivers/pikpak.md
  docs/guide/drivers/thunder.md
  docs/zh/guide/README.md
  docs/zh/guide/advanced/alias.md
  docs/zh/guide/advanced/s3.md
  docs/zh/guide/drivers/123.md
  docs/zh/guide/drivers/139.md
  docs/zh/guide/drivers/163music.md
  docs/zh/guide/drivers/189.md
  docs/zh/guide/drivers/Alist V2 V3.md
  docs/zh/guide/drivers/Crypt.md
  docs/zh/guide/drivers/alias.md
  docs/zh/guide/drivers/common.md
  docs/zh/guide/drivers/mega.md
  docs/zh/guide/drivers/pikpak.md
  docs/zh/guide/drivers/thunder.md
Labels: size/XXL
